# Generated by Django 4.1.7 on 2023-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'participant',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
