version: '3.9'

services:

  db_postgres:
    image: postgres:15.1
    container_name: postgres_farma
    volumes:
      - ./pgdata:/var/lib/postgresql/data1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"